# Generated by Django 3.2.3 on 2021-12-13 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='track_code',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('postOfficeIndex', models.CharField(max_length=6)),
                ('postOfficeName', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parcel')),
            ],
        ),
    ]
