# Generated by Django 3.2.3 on 2021-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211213_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='track_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
